"""Interface themes (6.0.28): Light (MegaNexus blue), Dark (black, for OLED TVs)
and Semi-dark (dark at the top around the small video, dark blue at the bottom).

The MegaNexus windows load their XML from script.nuvio/resources/skins/<folder>
(Default, Dark, Dim - the latter two generated by review/make_theme_variants.py).
The MegaNexus skin follows through a skin string (HUB banner) and its Kodi
colour theme (dialogs, buttons). The screensaver uses the theme's background.
"""
THEMES = ('light', 'dark', 'dim')
DEFAULT = 'light'
SETTING = 'nuvio_theme'
LABELS = {'light': 'Light · MegaNexus blue', 'dark': 'Dark · black for OLED TVs',
          'dim': 'Semi-dark · dark top, dark blue bottom'}
FOLDERS = {'light': 'Default', 'dark': 'Dark', 'dim': 'Dim'}
MEDIA = 'special://home/addons/script.nuvio/resources/media/'
BANNERS = {'light': 'nuvio_banner.png', 'dark': 'nuvio_banner_dark.png', 'dim': 'nuvio_banner_dim.png'}
SKIN_COLORS = {'light': 'SKINDEFAULT', 'dark': 'dark', 'dim': 'dim'}  # skin.nuvio/colors/<name>.xml
SKIN_STRING = 'nuvio.theme'
# Posters and catalog art are drawn slightly see-through over the glass boxes.
OPACITY_SETTING = 'nuvio_card_opacity'
OPACITY_LEVELS = ('0', '10', '20', '30')   # percent transparency; '0' = off
OPACITY_DEFAULT = '10'
OPACITY_LABELS = {'0': 'Off', '10': '10 % · subtle', '20': '20 %', '30': '30 %'}
OPACITY_PROPERTY = 'nuvio.card_opacity'    # read by the windows (Window(Home).Property)


def _addon(addon=None):
    if addon is not None:
        return addon
    import xbmcaddon
    return xbmcaddon.Addon('plugin.video.nuviohub')


def current(addon=None):
    try:
        value = (_addon(addon).getSetting(SETTING) or '').strip()
    except Exception:
        value = ''
    return value if value in THEMES else DEFAULT


def folder(addon=None):
    """Skin folder for xbmcgui.WindowXML(..., folder(), '1080i')."""
    return FOLDERS[current(addon)]


def banner(addon=None):
    return MEDIA + BANNERS[current(addon)]


def card_opacity(addon=None):
    try:
        value = (_addon(addon).getSetting(OPACITY_SETTING) or '').strip()
    except Exception:
        value = ''
    return value if value in OPACITY_LEVELS else OPACITY_DEFAULT


def set_card_opacity(level, addon=None):
    if level not in OPACITY_LEVELS:
        raise ValueError('Unknown transparency.')
    addon = _addon(addon)
    addon.setSetting(OPACITY_SETTING, level)
    _publish_opacity(level)


def _publish_opacity(level):
    import xbmcgui
    xbmcgui.Window(10000).setProperty(OPACITY_PROPERTY, level)


def _rpc(method, params):
    import json
    import xbmc
    reply = json.loads(xbmc.executeJSONRPC(json.dumps({'jsonrpc': '2.0', 'id': 1, 'method': method, 'params': params})))
    return reply.get('result')


def sync(addon=None):
    """Make the MegaNexus skin match the chosen theme (cheap when it already does).
    Only touches Kodi's colour-theme setting while the MegaNexus skin is active."""
    import xbmc
    theme = current(addon)
    _publish_opacity(card_opacity(addon))
    if xbmc.getInfoLabel('Skin.String(%s)' % SKIN_STRING) != theme:
        xbmc.executebuiltin('Skin.SetString(%s,%s)' % (SKIN_STRING, theme))
    if xbmc.getSkinDir() != 'skin.nuvio':
        return
    try:
        colors = (_rpc('Settings.GetSettingValue', {'setting': 'lookandfeel.skincolors'}) or {}).get('value')
        if colors != SKIN_COLORS[theme]:
            _rpc('Settings.SetSettingValue', {'setting': 'lookandfeel.skincolors', 'value': SKIN_COLORS[theme]})
    except Exception:
        pass


def apply(theme, addon=None):
    if theme not in THEMES:
        raise ValueError('Unknown theme.')
    addon = _addon(addon)
    addon.setSetting(SETTING, theme)
    try:
        from . import settings_cache
        settings_cache.invalidate()
    except Exception:
        pass
    sync(addon)
